### ISSUE TITLE
KeyError: 'Station'

### ISSUE THREAD

**Issue by seal-git** [seal-git/22zemi#310]
python-flask  | thread9: Guest Lounge Atrium/東京ステーションホテル, ChIJ55FqKPCLGGAR2GqcmoYJNzM
python-flask  | calc_priority_thread: waiting
python-flask  | data_num 71
python-flask  | calc_priority_thread: end
python-flask  | set_filter_params: params renewed
python-flask  | yahoo_local_search with params
python-flask  | Exception in thread Thread-584:
python-flask  | Traceback (most recent call last):
python-flask  |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
python-flask  |     self.run()
python-flask  |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
python-flask  |     self._target(*self._args, **self._kwargs)
python-flask  |   File "/workspace/app/models.py", line 327, in thread_info
python-flask  |     _ = recommend.recommend_main(fetch_group, group_id, user_id)
python-flask  |   File "/workspace/app/recommend.py", line 953, in recommend_main
python-flask  |     restaurants_info = call_api.search_restaurants_info(fetch_group,
python-flask  |   File "/workspace/app/call_api.py", line 55, in search_restaurants_info
python-flask  |     restaurants_info = api_functions.yahoo_local_search(params)
python-flask  |   File "/workspace/app/api_functions.py", line 168, in yahoo_local_search
python-flask  |     r_info.station = [s["Name"] for s in feature["Property"]["Station"]]
python-flask  | KeyError: 'Station'

**Comment by seal-git** [comment]
再現条件が書いてないので取り下げ
